name: Linting

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  linting:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      
      - name: Install Yarn packages
        run: yarn install
      
      - name: Run linters
        run: yarn lint:strict
