name: Testing

on:
  push:
    branches:
      - dev
  pull_request:
    types: [opened, reopened, synchronize]

permissions: read-all

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16
    
    - name: Install Yarn packages
      run: yarn install
    
    - name: Build project
      run: yarn build
